---
- name: DNS server playbook
  hosts: 192.168.122.193
  become: true

  tasks:
    - name: Install dns service
      ansible.builtin.dnf:
        name:
          - bind
          - bind-utils
        state: latest

    - name: Copy dns main config
      ansible.builtin.template:
        src: ./templates/named.conf.j2
        dest: /etc/named.conf

    - name: Copy dns forward zone configs
      ansible.builtin.template:
        src: ./forward.lab.j2
        dest: /var/named/forward.lab
        owner: named
        group: named

    - name: Copy dns reverse zone configs
      ansible.builtin.template:
        src: ./templates/reverse.lab.j2
        dest: /var/named/reverse.lab
        owner: named
        group: named

    - name: Start and enable DNS
      ansible.builtin.service:
        name: named
        state: restarted
        enabled: true

    - name: Enable DNS firewall rule
      ansible.posix.firewalld:
        service: dns
        state: enabled
        permanent: true
        immediate: true

    - name: Run dig to test configuration
      ansible.builtin.command:
        cmd: "dig masterdns.internal.virtnet @192.168.122.193"
      changed_when: false
